name = "Kestrel"
uuid = "72538bae-ab4f-4aee-8124-a7c707179a74"
authors = ["pekochan069"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
